### ISSUE TITLE
Problematic emails 2

### ISSUE THREAD

**Issue by KrzysztofBarbarski** [jstedfast/EmailValidation#37]
I would like to ask about another email address, which makes some issues.

I found that the emails below are treated like proper addresses, but is impossible to send a message:
- email@[123.123.123.123]
- "email"@example.com
- test/test@test.com
- mailhost!username@example.org

Same situation but in reverse, this looks like a proper address, but is treated as invalid:
- 1234567890123456789012345678901234567890123456789012345678901234+x@example.com

Would you be able to verify that?

**Comment by jstedfast** [comment]
> email@[123.123.123.123]

This is valid syntax. See [rfc2822, section 3.4.1](https://www.rfc-editor.org/rfc/rfc2822#section-3.4.1). Specifically, look at the definition of `domain-literal`.

> "email"@example.com

Again, this is valid. See the same RFC/section - specifically the definition of `local-part`.

> test/test@test.com

Yep. Valid. See the same section again and the definition of `local-part` (note that it can be a `dot-atom` and then go to [section 3.2.4](https://www.rfc-editor.org/rfc/rfc2822#section-3.2.4) to see the definition of a `dot-atom`. A `/` is valid.

> mailhost!username@example.org

Same as above. A `!` is valid.

> Same situation but in reverse, this looks like a proper address, but is treated as invalid:
> 1234567890123456789012345678901234567890123456789012345678901234+x@example.com

Not valid because the `local-part` exceeds the max length. See [rfc2821, section 4.5.3.1](https://www.rfc-editor.org/rfc/rfc2821#section-4.5.3.1) to note that the maximum length of a `local-part` allowed by SMTP is 64 characters but the `local-part` in your example is 66 characters.

**Comment by KrzysztofBarbarski** [comment]
Okay, thank for you effort
